// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Backend.Models.BestPractice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("Objective")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepTaskName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StepuserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.HasIndex("StepuserId", "StepTaskName", "StepNumber");

                    b.ToTable("BestPractices");
                });

            modelBuilder.Entity("Backend.Models.CommonDifficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cause")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solution")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepTaskName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StepuserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.HasIndex("StepuserId", "StepTaskName", "StepNumber");

                    b.ToTable("CommonDifficulties");
                });

            modelBuilder.Entity("Backend.Models.Department", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeptName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Function")
                        .HasColumnType("TEXT");

                    b.HasKey("userId", "DeptName");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("userId", "Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Backend.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeuserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskDeptName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskuserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.HasIndex("EmployeeuserId", "EmployeeId");

                    b.HasIndex("TaskuserId", "TaskDeptName", "TaskName");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Backend.Models.Step", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentDeptName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentuserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeptName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDeptName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName1")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskuserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("userId", "TaskName", "Number");

                    b.HasIndex("DepartmentuserId", "DepartmentDeptName");

                    b.HasIndex("TaskuserId", "TaskDeptName", "TaskName1");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("Backend.Models.Task", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeptName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("userId", "DeptName", "TaskName");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.BestPractice", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Step", "Step")
                        .WithMany("BestPractice")
                        .HasForeignKey("StepuserId", "StepTaskName", "StepNumber");
                });

            modelBuilder.Entity("Backend.Models.CommonDifficulty", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Step", "Step")
                        .WithMany("CommonDifficulty")
                        .HasForeignKey("StepuserId", "StepTaskName", "StepNumber");
                });

            modelBuilder.Entity("Backend.Models.Department", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Department")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Employee", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Employee")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Schedule", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Employee", "Employee")
                        .WithMany("Schedule")
                        .HasForeignKey("EmployeeuserId", "EmployeeId");

                    b.HasOne("Backend.Models.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskuserId", "TaskDeptName", "TaskName");
                });

            modelBuilder.Entity("Backend.Models.Step", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentuserId", "DepartmentDeptName");

                    b.HasOne("Backend.Models.Task", "Task")
                        .WithMany("Step")
                        .HasForeignKey("TaskuserId", "TaskDeptName", "TaskName1");
                });

            modelBuilder.Entity("Backend.Models.Task", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Department", "Department")
                        .WithMany("Task")
                        .HasForeignKey("userId", "DeptName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
